# stream：RabbitMQ 多协议透传（AMQP 由 35672 回归默认）
server { listen 5672;  proxy_pass rabbitmq:5672; }   # AMQP
server { listen 1883;  proxy_pass rabbitmq:1883; }   # MQTT
server { listen 15675; proxy_pass rabbitmq:15675; }  # MQTT over WebSocket
