# Adminer 数据库管理（原生端口 8080）
server {
    listen 8080;
    server_name adminer.glseven.local;
    location / {
        proxy_pass http://adminer:8080;
        include /etc/nginx/snippets/proxy.conf;
    }
}
