# ELK：Kibana UI（5601）与 ES API（9200）同域名不同端口
server {
    listen 5601;
    server_name elk.glseven.local;
    location / {
        proxy_pass http://elk:5601;
        include /etc/nginx/snippets/proxy.conf;
    }
}

server {
    listen 9200;
    server_name elk.glseven.local;
    location / {
        proxy_pass http://elk:9200;
        include /etc/nginx/snippets/proxy.conf;
    }
}
