# iPTV 直播源管理（原生端口 1905，独占端口无需 Host 分流）
server {
    listen 1905;
    server_name iptv.glseven.local;
    location / {
        proxy_pass http://iptv:1905;
        include /etc/nginx/snippets/proxy.conf;
    }
}
