# mongo-express MongoDB Web 管理（原生端口 8081）
server {
    listen 8081;
    server_name mongo-express.glseven.local;
    location / {
        proxy_pass http://mongo-express:8081;
        include /etc/nginx/snippets/proxy.conf;
    }
}
