# Nexus3 Web UI（原生端口 8081，与 mongo-express 同端口按 Host 分流；Registry 5000 走 stream）
server {
    listen 8081;
    server_name nexus3.glseven.local;
    location / {
        proxy_pass http://nexus3:8081;
        include /etc/nginx/snippets/proxy.conf;
    }
}
