# Prometheus 指标查询（原生端口 9090）
server {
    listen 9090;
    server_name prometheus.glseven.local;
    location / {
        proxy_pass http://prometheus:9090;
        include /etc/nginx/snippets/proxy.conf;
    }
}
