# RabbitMQ 管理台（原生端口 15672；AMQP/MQTT 走 stream-conf.d/rabbitmq.conf）
server {
    listen 15672;
    server_name rabbitmq.glseven.local;
    location / {
        proxy_pass http://rabbitmq:15672;
        include /etc/nginx/snippets/proxy.conf;
    }
}
