version: "3.6"

networks:
  glseven:
    external: true

services:
  mysql:
    image: mysql
    container_name: mysql
    hostname: mysql
    restart: always
    command:
      - default-authentication-plugin=mysql_native_password
      - character-set-server=utf8mb4
      - collation-server=utf8mb4_unicode_ci
    env_file:
      - common/env/common.env
      - common/env/mysql.env
    volumes:
      - ${DOCKER_VOLUME}/mysql/data:/var/lib/mysql
      - ${DOCKER_VOLUME}/mysql/conf.d:/etc/mysql/conf.d
      - ./mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    networks:
      glseven:
        ipv4_address: 172.18.1.2
    ports:
      - "3306:3306"
      - "33060:33060"

  redis:
    image: redis
    container_name: redis
    hostname: redis
    restart: always
    command:
      - redis-server --appendonly yes
    env_file:
      - common/env/common.env
    volumes:
      - ${DOCKER_VOLUME}/redis/data:/data
    networks:
      glseven:
        ipv4_address: 172.18.1.3
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    hostname: rabbitmq
    restart: always
    env_file:
      - common/env/common.env
    volumes:
      - ${DOCKER_VOLUME}/rabbitmq/data:/var/lib/rabbitmq
    networks:
      glseven:
        ipv4_address: 172.18.1.4
    ports:
      - "4369:4369"
      - "5671:5671"
      - "5672:5672"
      - "15671:15671"
      - "15672:15672"
      - "25672:25672"

  portainer:
    image: portainer/portainer
    container_name: portainer
    hostname: portainer
    restart: always
    env_file:
      - common/env/common.env
    volumes:
      - ${DOCKER_VOLUME}/portainer/data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      glseven:
        ipv4_address: 172.18.1.5
    ports:
      - "9000:9000"

  nacos:
    image: nacos/nacos-server
    container_name: nacos
    hostname: nacos
    restart: always
    env_file:
      - common/env/common.env
      - common/env/nacos.env
    volumes:
      - ${DOCKER_VOLUME}/nacos/logs:/home/nacos/logs
      - ./nacos/config/custom.properties:/home/nacos/init.d/custom.properties
    networks:
      glseven:
        ipv4_address: 172.18.1.6
    external_links:
      - mysql
    ports:
      - "8848:8848"
      - "9555:9555"

  xxl-job-admin:
    image: xuxueli/xxl-job-admin:2.3.0
    container_name: xxl-job-admin
    hostname: xxl-job-admin
    restart: always
    env_file:
      - common/env/common.env
    volumes:
      - ${DOCKER_VOLUME}/xxl-job-admin/logs:/data/applogs
      - ./xxl-job-admin/application.properties:/application.properties
    networks:
      glseven:
        ipv4_address: 172.18.1.7
    external_links:
      - mysql
    ports:
      - "8381:8080"