networks:
  glseven:
    external: true

services:
  nacos:
    image: nacos/nacos-server
    container_name: nacos
    hostname: nacos
    restart: always
    env_file:
      - common/env/common.env
      - common/env/nacos.env
    volumes:
      - ${DOCKER_VOLUME}/nacos/logs:/home/nacos/logs
      - ./nacos/config/custom.properties:/home/nacos/init.d/custom.properties
    networks:
      glseven:
        ipv4_address: 172.18.4.1
    external_links:
      - mysql
    ports:
      - "48081:8080"
      - "8848:8848"
      - "9848:9848"

  xxl-job-admin:
    image: xuxueli/xxl-job-admin:3.2.0
    container_name: xxl-job-admin
    hostname: xxl-job-admin
    restart: always
    env_file:
      - common/env/common.env
    volumes:
      - ${DOCKER_VOLUME}/xxl-job-admin/logs:/data/applogs
      - ./xxl-job-admin/application.properties:/application.properties
    networks:
      glseven:
        ipv4_address: 172.18.4.2
    external_links:
      - mysql
    ports:
      - "48080:8080"