version: "3.6"

networks:
  glseven:
    external: true

services:
  portainer:
    image: portainer/portainer-ce
    container_name: portainer
    hostname: portainer
    restart: always
    env_file:
      - common/env/common.env
    volumes:
      - ${DOCKER_VOLUME}/portainer/data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      glseven:
        ipv4_address: 172.18.3.1
    ports:
      - "9000:9000"

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    hostname: prometheus
    restart: always
    env_file:
      - common/env/common.env
    volumes:
      - ./prometheus/conf/prometheus.yml:/etc/prometheus/prometheus.yml
      - ${DOCKER_VOLUME}/prometheus/data:/prometheus
    networks:
      glseven:
        ipv4_address: 172.18.3.2
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana
    container_name: grafana
    hostname: grafana
    restart: always
    env_file:
      - common/env/common.env
    volumes:
      - ./grafana/conf/provisioning:/etc/grafana/provisioning
      - ./grafana/conf/dashboards:/var/lib/grafana/dashboards
      - ./grafana/conf/config/grafana.ini:/etc/grafana/grafana.ini
    networks:
      glseven:
        ipv4_address: 172.18.3.3
    ports:
      - "3000:3000"