version: "3.6"

networks:
  glseven:
    external: true

services:
  nacos:
    image: nacos/nacos-server:v2.3.0
    container_name: nacos
    hostname: nacos
    restart: always
    env_file:
      - common/env/common.env
      - common/env/nacos.env
    volumes:
      - ${DOCKER_VOLUME}/nacos/logs:/home/nacos/logs
      - ./nacos/config/custom.properties:/home/nacos/init.d/custom.properties
    networks:
      glseven:
        ipv4_address: 172.18.4.1
    external_links:
      - mysql
    ports:
      - "8848:8848"
      - "9555:9555"
      - "9848:9848"
      - "9849:9849"

  xxl-job-admin:
    image: xuxueli/xxl-job-admin:2.4.0
    container_name: xxl-job-admin
    hostname: xxl-job-admin
    restart: always
    env_file:
      - common/env/common.env
    volumes:
      - ${DOCKER_VOLUME}/xxl-job-admin/logs:/data/applogs
      - ./xxl-job-admin/application.properties:/application.properties
    networks:
      glseven:
        ipv4_address: 172.18.4.2
    external_links:
      - mysql
    ports:
      - "48080:8080"

  keycloak:
    image: jboss/keycloak:16.1.1
    container_name: keycloak
    hostname: keycloak
    restart: always
    env_file:
      - common/env/common.env
      - common/env/keycloak.env
    networks:
      glseven:
        ipv4_address: 172.18.4.3
    external_links:
      - mysql
    ports:
      - "48081:8080"

  apisix-dashboard:
    image: apache/apisix-dashboard:3.0.1-alpine
    container_name: apisix-dashboard
    hostname: apisix-dashboard
    restart: always
    env_file:
      - common/env/common.env
    volumes:
      - ./apisix-dashboard/conf/conf.yaml:/usr/local/apisix-dashboard/conf/conf.yaml
    networks:
      glseven:
        ipv4_address: 172.18.4.4
    ports:
      - "49000:9000"

  apisix:
    image: apache/apisix:3.7.0-debian
    container_name: apisix
    hostname: apisix
    restart: always
    env_file:
      - common/env/common.env
    volumes:
      - ${DOCKER_VOLUME}/apisix/log:/usr/local/apisix/logs
      - ./apisix/conf/config.yaml:/usr/local/apisix/conf/config.yaml:ro
    networks:
      glseven:
        ipv4_address: 172.18.4.5
    external_links:
      - etcd
    ports:
      - "9180:9180"
      - "9080:9080"
      - "9091:9091"
      - "9443:9443"
      - "9092:9092"