name: devops

networks:
  glseven:
    external: true

services:

  # DevOps 172.18.6.x ==================================================================================================

  nexus3:
    image: sonatype/nexus3:3.90.1
    container_name: nexus3
    hostname: nexus3
    restart: always
    env_file:
      - common/env/common.env
    volumes:
      - ${DOCKER_VOLUME:-/docker/glseven}/nexus3/data:/nexus-data
    networks:
      glseven:
        ipv4_address: 172.18.6.1
    ports:
      - "5000:5000"   # Docker Registry
      - "8081:8081"   # Nexus Web UI
