networks:
  glseven:
    external: true

services:

  # Manager 172.18.5.x =================================================================================================

  portainer:
    image: portainer/portainer-ce:2.21.5
    container_name: portainer
    hostname: portainer
    restart: always
    env_file:
      - common/env/common.env
    volumes:
      - ${DOCKER_VOLUME}/portainer/data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      glseven:
        ipv4_address: 172.18.5.1
    ports:
      - "9000:9000"
