name: messaging

networks:
  glseven:
    external: true

services:

  # Messaging 172.18.2.x ==============================================================================================

  rabbitmq:
    image: rabbitmq:4.2.4-management
    container_name: rabbitmq
    hostname: rabbitmq
    restart: always
    env_file:
      - common/env/common.env
      - common/env/rabbitmq.env
    volumes:
      - ${DOCKER_VOLUME:-/docker/glseven}/rabbitmq/data:/var/lib/rabbitmq
      - ./rabbitmq/enabled_plugins:/etc/rabbitmq/enabled_plugins
    networks:
      glseven:
        ipv4_address: 172.18.2.1
    ports:
      - "35672:5672"   # AMQP
      - "15672:15672"  # Management UI
      - "1883:1883"    # MQTT
      - "15675:15675"  # MQTT over WebSocket

  kafka:
    image: apache/kafka:4.2.0
    container_name: kafka
    hostname: kafka
    restart: always
    env_file:
      - common/env/common.env
      - common/env/kafka.env
    volumes:
      - ${DOCKER_VOLUME:-/docker/glseven}/kafka/config:/mnt/shared/config
      - ${DOCKER_VOLUME:-/docker/glseven}/kafka/data:/var/lib/kafka/data
      - ${DOCKER_VOLUME:-/docker/glseven}/kafka/secrets:/etc/kafka/secrets
    networks:
      glseven:
        ipv4_address: 172.18.2.2
    ports:
      - "9092:9092"
