version: "3.6"

networks:
  glseven:
    external: true

services:
  zookeeper-1:
    image: zookeeper
    container_name: zookeeper-1
    hostname: zookeeper-1
    restart: always
    volumes:
      - ${DOCKER_VOLUME}/zkcluster/zookeeper-1/logs:/logs
      - ${DOCKER_VOLUME}/zkcluster/zookeeper-1/data:/data
      - ${DOCKER_VOLUME}/zkcluster/zookeeper-1/datalog:/datalog
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=0.0.0.0:2888:3888 server.2=zookeeper-2:2888:3888 server.3=zookeeper-3:2888:3888
    networks:
      glseven:
        ipv4_address: 172.18.2.2
    ports:
      - "2184:2181"

  zookeeper-2:
    image: zookeeper
    container_name: zookeeper-2
    hostname: zookeeper-2
    restart: always
    volumes:
      - ${DOCKER_VOLUME}/zkcluster/zookeeper-2/logs:/logs
      - ${DOCKER_VOLUME}/zkcluster/zookeeper-2/data:/data
      - ${DOCKER_VOLUME}/zkcluster/zookeeper-2/datalog:/datalog
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.1=zookeeper-1:2888:3888 server.2=0.0.0.0:2888:3888 server.3=zookeeper-3:2888:3888
    networks:
      glseven:
        ipv4_address: 172.18.2.3
    ports:
      - "2185:2181"
  
  zookeeper-3:
    image: zookeeper
    container_name: zookeeper-3
    hostname: zookeeper-3
    restart: always
    volumes:
      - ${DOCKER_VOLUME}/zkcluster/zookeeper-3/logs:/logs
      - ${DOCKER_VOLUME}/zkcluster/zookeeper-3/data:/data
      - ${DOCKER_VOLUME}/zkcluster/zookeeper-3/datalog:/datalog
    environment:
      ZOO_MY_ID: 3
      ZOO_SERVERS: server.1=zookeeper-1:2888:3888 server.2=zookeeper-2:2888:3888 server.3=0.0.0.0:2888:3888
    networks:
      glseven:
        ipv4_address: 172.18.2.4
    ports:
      - "2186:2181"

  kafka-1:
    image: wurstmeister/kafka
    container_name: kafka-1
    hostname: kafka-1
    restart: always
    privileged: true
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ADVERTISED_HOST_NAME: kafka-1
      KAFKA_LISTENERS: PLAINTEXT://kafka-1:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-1:9092
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-1:2181/kafka-1,zookeeper-2:2181/kafka-1,zookeeper-3:2181/kafka-1
    volumes:
      - ${DOCKER_VOLUME}/kafkaCluster/kafka-1/logs:/kafka
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      glseven:
        ipv4_address: 172.18.2.5
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper-1
      - zookeeper-2
      - zookeeper-3

  kafka-2:
    image: wurstmeister/kafka
    container_name: kafka-2
    hostname: kafka-2
    restart: always
    privileged: true
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ADVERTISED_HOST_NAME: kafka-2
      KAFKA_LISTENERS: PLAINTEXT://kafka-2:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-2:9093
      KAFKA_ADVERTISED_PORT: 9093
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-1:2181/kafka-2,zookeeper-2:2181/kafka-2,zookeeper-3:2181/kafka-2
    volumes:
      - ${DOCKER_VOLUME}/kafkaCluster/kafka-2/logs:/kafka
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      glseven:
        ipv4_address: 172.18.2.6
    ports:
      - "9093:9093"
    depends_on:
      - zookeeper-1
      - zookeeper-2
      - zookeeper-3

  kafka-3:
    image: wurstmeister/kafka
    container_name: kafka-3
    hostname: kafka-3
    restart: always
    privileged: true
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_ADVERTISED_HOST_NAME: kafka-3
      KAFKA_LISTENERS: PLAINTEXT://kafka-3:9094
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-3:9094
      KAFKA_ADVERTISED_PORT: 9094
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-1:2181/kafka-3,zookeeper-2:2181/kafka-3,zookeeper-3:2181/kafka-3
    volumes:
      - ${DOCKER_VOLUME}/kafkaCluster/kafka-3/logs:/kafka
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      glseven:
        ipv4_address: 172.18.2.7
    ports:
      - "9094:9094"
    depends_on:
      - zookeeper-1
      - zookeeper-2
      - zookeeper-3