name: portal

networks:
  glseven:
    external: true

services:

  # Portal 172.18.6.x ==================================================================================================

  nginx:
    image: nginx:1.30.4
    container_name: nginx
    hostname: nginx
    restart: always
    env_file:
      - common/env/common.env
    volumes:
      - ./portal/conf/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./portal/html:/usr/share/nginx/html:ro
    networks:
      glseven:
        ipv4_address: 172.18.6.1
    ports:
      - "8000:80"
