version: "3.6"

networks:
  glseven:
    external: true

services:

  # DevOps环境 172.18.2网段 8000端口段 ==================================================================================
  nexus3:
    image: sonatype/nexus3
    container_name: nexus3
    hostname: nexus3
    restart: always
    privileged: true
    env_file:
      - common/env/common.env
    volumes:
      - ${DOCKER_VOLUME}/nexus3/data:/nexus-data
    networks:
      glseven:
        ipv4_address: 172.18.2.1
    ports:
      - "5000:5000"
      - "8081:8081"


  pandora:
    image: pengzhile/pandora
    container_name: pandora
    hostname: pandora
    restart: always
    env_file:
      - common/env/common.env
      - common/env/pandora.env
    volumes:
      - ${DOCKER_VOLUME}/pandora/data:/data
    networks:
      glseven:
        ipv4_address: 172.18.2.2
    ports:
      - "8899:8899"