name: ai

networks:
  glseven:
    external: true

services:

  # AI 172.18.9.x ======================================================================================================

  ollama:
    image: ollama/ollama:0.17.7
    container_name: ollama
    hostname: ollama
    restart: always
    tty: true
    env_file:
      - common/env/common.env
      - common/env/ollama.env
    volumes:
      - ${DOCKER_VOLUME:-/docker/glseven}/ollama:/root/.ollama
    networks:
      glseven:
        ipv4_address: 172.18.9.1
    ports:
      - "11434:11434"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:11434/api/version" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    deploy:
      resources:
        limits:
          cpus: "4.0"
          memory: 8G
        reservations:
          devices:
            - driver: nvidia
              capabilities: [ gpu ]
              count: all

  open-webui:
    image: ghcr.io/open-webui/open-webui:0.8.9
    container_name: open-webui
    hostname: open-webui
    restart: always
    env_file:
      - common/env/common.env
      - common/env/open-webui.env
    volumes:
      - ${DOCKER_VOLUME:-/docker/glseven}/open-webui/data:/app/backend/data
    depends_on:
      ollama:
        condition: service_healthy
    networks:
      glseven:
        ipv4_address: 172.18.9.2
    ports:
      - "8080:8080"